### ISSUE TITLE
ClassCastException: java.lang.Float cannot be cast to java.lang.Integer

### ISSUE THREAD

**Issue by hvdwolf** [lbdroid/GPSSpeedFix#3]
The GPSSpeedFix as such works fine now with the 3 averages instead of 5 (or 1). As it worked fine I did not even look in the Xposed logs, until last Saturday and this morning again.

See below: Does the system really expects an integer back?
Or is it something stupid in my modifications of the code?

I also see from your code that you did not apply my last pull request, as you wanted a cleaner request.
I will follow your advise about "In the future..", but as you already applied the pull request including that  "remove moving avarages", how do you expect a cleaner pull request from me than the one with only the removal of my last patch in the previous pull request? I can do the "git reset --hard HEAD~1" on my local repo, but not on your repo.

Error in the Xposed logs (a lot of the same error)
```
03-01 10:39:04.025 E/Xposed  (20243): java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Integer
03-01 10:39:04.025 E/Xposed  (20243): 	at tk.rabidbeaver.gpsspeedfix.GPSSpeedFixModule$1.beforeHookedMethod(GPSSpeedFixModule.java:59)
03-01 10:39:04.025 E/Xposed  (20243): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
03-01 10:39:04.025 E/Xposed  (20243): 	at com.android.server.location.GpsLocationProvider.reportLocation(<Xposed>)
```

**Comment by gtxaspec** [comment]
I was about to post this as well, thanks!  I forgot to report this weeks ago.

**Comment by lbdroid** [comment]
hvdwolf: you need to use 'git revert <commit>' to back out a commit, not manually unwrite it. On your branch, start by resetting away the 'unwrite' commit, be 'git reset --hard HEAD~1' then 'git push --force'. Then do a revert to undo the bad commit.

As for that error message, it's perplexing on a number of levels, in particular, since there is no use of Float (class), just float (primitive data type). The other part that is perplexing is that on that line, something is being cast *to* a float, not from one.

This is probably some kind of crazy to do with xposed.
